name       : libclc
version    : 15.0.7
release    : 2
source     :
    - https://github.com/llvm/llvm-project/releases/download/llvmorg-15.0.7/libclc-15.0.7.src.tar.xz : 35731fea7be224f21acf5bf3cd9f0ed058bf4ada5eceaf7f10ee96e139bd3389
license    : MIT
component  : programming.library
summary    : libclc is an open source implementation of the OpenCL 1.1 Specification
description: |
    libclc is an open source, BSD licensed implementation of the library requirements of the OpenCL C programming language, as specified by the OpenCL 1.1 Specification.
emul32     : yes
clang      : yes
builddeps  :
    - pkgconfig(LLVMSPIRVLib)
    - llvm-32bit-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
