name       : libclc
version    : 2019.05.27
release    : 1
source     :
    - git|https://github.com/llvm-mirror/libclc : 9f6204ec04a8cadb6bef57caa71e3161c4f398f2
license    : MIT
component  : programming.library
summary    : libclc is an open source implementation of the OpenCL 1.1 Specification
description: |
    libclc is an open source, BSD licensed implementation of the library requirements of the OpenCL C programming language, as specified by the OpenCL 1.1 Specification.
emul32     : yes
clang      : yes
setup      : |
    ./configure.py --prefix=/usr --libexecdir=%libdir%/clc
build      : |
    %make
install    : |
    %make_install
